resolver: lts-13.8
packages:
- hgit
- hgit-ext

extra-deps:
- github: pkinsky/merkle-schemes
  commit: b5e1c5b120300562d19fa33c95d4efcdfedea7a5
  subdirs:
    - merkle-schemes
    - merkle-schemes-ext
