resolver: lts-13.8
packages:
- .

extra-deps:
- ../merkle-schemes/merkle-schemes
- ../merkle-schemes/merkle-schemes-ext
- ../merkle-schemes/merkle-schemes-higher
- github: obsidiansystems/aeson-gadt-th
  commit: 0f8263aa5fb59d296874bd505551c81fedb115d1
