resolver: lts-13.8
packages:
- .

extra-deps:
# - github: inanna-malick/merkle-schemes
#   commit: 4eac64f4df12ea7d1d1f3bb34010424db19e0a9e
# - location: ../merkle-schemes
#   subdirs:
#     - merkle-schemes
#     - merkle-schemes-higher
- ../merkle-schemes/merkle-schemes
- ../merkle-schemes/merkle-schemes-higher
