resolver: lts-13.8
packages:
- .

extra-deps:
# - github: inanna-malick/merkle-schemes
#   commit: 4eac64f4df12ea7d1d1f3bb34010424db19e0a9e
- ../merkle-schemes/merkle-schemes
- ../merkle-schemes/merkle-schemes-ext
- ../merkle-schemes/merkle-schemes-higher
- github: obsidiansystems/aeson-gadt-th
  commit: 0f8263aa5fb59d296874bd505551c81fedb115d1
